analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  delta_v: 0.1
  dexp: 1.0
  dropout: 0.5
  input_layer: false
  k: 20
  knn_mode: s
  method: lnpcc
  n_hidden: 64
  n_layer: 2
  n_repeats: 10
  norm_info:
  output_layer: false
  p_grd: 0.3
  unc_rem: 0.5
  unc_rel: 0.5
  uniformLabeled: false
training:
  criterion: metric
  debug: false
  lr: 0.01
  n_epochs: 200
  patience:
  weight_decay: 0.0005
